name: Run Tests

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3    
      - name: Build libpolars
        run: cargo build --verbose
        working-directory: ./c-polars
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.9
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          coverage: false
