name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: Compile libpolars
        id: compile
        uses: rust-build/rust-build.action@v1.4.3
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
          SRC_DIR: c-polars
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.9
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          coverage: false
